version: '3.5'

networks: 
    backend:
        driver: bridge
    frontend:
        driver: bridge

services:
### MySQL ###
    mysql:
        image: mysql:5.7.33
        restart: always
        command: [
            '--character-set-server=utf8',
        ]
        environment:
            MYSQL_ROOT_PASSWORD: example
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
            - ./init:/docker-entrypoint-initdb.d/
        networks: 
            - backend
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # 执行的命令

### Halo ###
    halo:
        image: halohub/halo:latest
        restart: always
        volumes:
            - ./halo:/root/.halo
        networks: 
            - backend
        links:
            - mysql
            


### Nginx ###
    nginx:
        build:
            context: ./nginx
        restart: always
        networks:
            - backend
            - frontend
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/sites:/etc/nginx/sites
            - ./nginx/logs:/var/log/nginx
            - ./nginx/ssls:/etc/nginx/ssls
        links:
            - halo


