version: '3.8'

networks: 
    backend:
        driver: bridge
    frontend:
        driver: bridge

services:
### MySQL ###
    mysql:
        image: mysql:5.7.33
        restart: always
        command: [
            '--character-set-server=utf8',
        ]
        environment:
            MYSQL_ROOT_PASSWORD: example
        volumes:
            - ./mysql:/var/lib/mysql
            - ./init:/docker-entrypoint-initdb.d/
        networks: 
            - backend

### Halo ###
    halo:
        image: halohub/halo:latest
        restart: always
        volumes:
            - ./halo:/root/.halo
        ports:
            - 9000:8090
        networks: 
            - backend
            - frontend
        links:
            - mysql
        


